version: "3.8"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - booking1
      - booking2    

  db:
    image: postgres:latest
    container_name: booking_db    
    restart: always
    env_file:
      - .env.docker
    ports:
      - '5432:5432'
    volumes:
      - postgresdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: booking_redis

  booking1:
    image: booking_app
    build:
      context: .
      network: host
    container_name: booking1
    env_file:
      - .env.prod
    depends_on: 
      - db
      - redis    
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8001:8000

  booking2:
    image: booking_app
    container_name: booking2
    env_file:
      - .env.prod
    depends_on: 
      - db
      - redis    
      - booking1
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"    
    ports:
      - 8002:8000 

  # celery:
  #   image: booking_app
  #   build:
  #     context: . 
  #     network: host
  #   container_name: booking_celery    
  #   command: ["/booking/docker/scripts/celery.sh", "celery"]    
  #   env_file:
  #     - .env.prod
  #   depends_on:
  #     - redis

  # flower:
  #   image: booking_app
  #   build:
  #     context: . 
  #     network: host
  #   container_name: booking_flower    
  #   command: ["/booking/docker/scripts/celery.sh", "flower"]    
  #   env_file:
  #     - .env.prod
  #   depends_on:
  #     - redis
  #   ports:
  #     - 5555:5555
      
volumes:
  postgresdata:

