"""Upgrade

Revision ID: 73c5a280f808
Revises: d1b02f8d8af8
Create Date: 2024-02-16 18:47:04.685303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c5a280f808'
down_revision: Union[str, None] = 'd1b02f8d8af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('providers_user_id_fkey', 'providers', type_='foreignkey')
    op.create_foreign_key(None, 'providers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'providers', type_='foreignkey')
    op.create_foreign_key('providers_user_id_fkey', 'providers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
