"""changed the customer id to auto-incremental

Revision ID: 9b2fd90a04ec
Revises: 42d239b4064b
Create Date: 2024-02-12 12:59:44.191237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2fd90a04ec'
down_revision: Union[str, None] = '42d239b4064b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
