"""Del user_id in Appointment model

Revision ID: fb9504eddf8b
Revises: a7f3784e752c
Create Date: 2024-02-18 23:54:51.046192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb9504eddf8b'
down_revision: Union[str, None] = 'a7f3784e752c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
